### ISSUE TITLE
How do I use this with Javascript?

### ISSUE THREAD

**Issue by wizaerd** [lettucebo/MvcDynamicForms#9]
Nevermind

**Comment by lettucebo** [comment]
Hi

Due to work relate problem, I can not deal this issue faster, Sorry about this

Use JavaScript with this is very simple

In the Field class have a property called: Key, Used to identify the field.

This property also reflect to html.

For example, I have a TextField and set the key

![image](https://cloud.githubusercontent.com/assets/891383/24117924/f5ddeb22-0de6-11e7-92e4-f321a6040475.png)

In the view I can get input id and name: prefix + Key
![image](https://cloud.githubusercontent.com/assets/891383/24117971/1e1e1314-0de7-11e7-846c-b21f3d342c01.png)

see the highlight section
